CREATE TABLE GRUPOAFILIADA 
(
  ID NUMBER(19,0) NOT NULL,
  CODIGO VARCHAR(100) NOT NULL,
  NOME VARCHAR(255) NOT NULL,
  
  CONSTRAINT grupoafiliadapk PRIMARY KEY (ID)
);

CREATE TABLE AFILIADA 
(
  ID NUMBER(19,0) NOT NULL,
  NOME VARCHAR(255) NOT NULL,
  CODIGO VARCHAR(50) NOT NULL,
  GRUPOAFILIADA_ID NOT NULL,
  
  CONSTRAINT afiliadapk PRIMARY KEY (ID),
  CONSTRAINT grupoafiliadafk FOREIGN KEY (GRUPOAFILIADA_ID) REFERENCES GRUPOAFILIADA(ID)
);

ALTER TABLE OPERADORA ADD AFILIADA_ID NUMBER(19,0);

ALTER TABLE OPERADORA
ADD CONSTRAINT operadoraafiliadafk
   FOREIGN KEY (AFILIADA_ID)
   REFERENCES AFILIADA (ID);
   


CREATE TABLE COMUTACAOAFILIADA 
(
  COMUTACAO_ID NUMBER(19,0) NOT NULL,
  AFILIADA_ID NUMBER(19,0) NOT NULL,
  
  CONSTRAINT comutacaoafiliada_afifk FOREIGN KEY (AFILIADA_ID) REFERENCES AFILIADA(ID),
  CONSTRAINT comutacaoafiliada_comfk FOREIGN KEY (COMUTACAO_ID) REFERENCES COMUTACAO(ID)
);


INSERT INTO GRUPOAFILIADA (ID, NOME, CODIGO) 
VALUES (HIBERNATE_SEQUENCE.nextVal,'EPTV', 'G06');

INSERT INTO GRUPOAFILIADA (ID, NOME, CODIGO) 
VALUES (HIBERNATE_SEQUENCE.nextVal, 'REDE INTER TV', 'G26');

INSERT INTO GRUPOAFILIADA (ID, NOME, CODIGO) 
VALUES (HIBERNATE_SEQUENCE.nextVal,'RBS', 'G01');

INSERT INTO GRUPOAFILIADA (ID, NOME, CODIGO) 
VALUES (HIBERNATE_SEQUENCE.nextVal,'REDE AMAZÔNICA', 'G02');

INSERT INTO GRUPOAFILIADA (ID, NOME, CODIGO) 
VALUES (HIBERNATE_SEQUENCE.nextVal,'RPC', 'G08');

INSERT INTO GRUPOAFILIADA (ID, NOME, CODIGO) 
VALUES (HIBERNATE_SEQUENCE.nextVal,'REDE CLUBE', 'G23');

INSERT INTO GRUPOAFILIADA (ID, NOME, CODIGO) 
VALUES (HIBERNATE_SEQUENCE.nextVal,'REDE ANHANGUERA', 'G09');

INSERT INTO GRUPOAFILIADA (ID, NOME, CODIGO) 
VALUES (HIBERNATE_SEQUENCE.nextVal,'TV ASA BRANCA', 'G27');

INSERT INTO GRUPOAFILIADA (ID, NOME, CODIGO) 
VALUES (HIBERNATE_SEQUENCE.nextVal,'REDE BAHIA', 'G00');

INSERT INTO GRUPOAFILIADA (ID, NOME, CODIGO) 
VALUES (HIBERNATE_SEQUENCE.nextVal,'REDE PARAÍBA', 'G17');

INSERT INTO GRUPOAFILIADA (ID, NOME, CODIGO) 
VALUES (HIBERNATE_SEQUENCE.nextVal,'REDE MATOGROSSENSE', 'G13');

INSERT INTO GRUPOAFILIADA (ID, NOME, CODIGO) 
VALUES (HIBERNATE_SEQUENCE.nextVal,'TV DIÁRIO', 'G11');

INSERT INTO GRUPOAFILIADA (ID, NOME, CODIGO) 
VALUES (HIBERNATE_SEQUENCE.nextVal,'TV FRONTEIRA', 'G15');

INSERT INTO GRUPOAFILIADA (ID, NOME, CODIGO) 
VALUES (HIBERNATE_SEQUENCE.nextVal,'REDE GAZETA', 'G10');

INSERT INTO GRUPOAFILIADA (ID, NOME, CODIGO) 
VALUES (HIBERNATE_SEQUENCE.nextVal,'TV GAZETA DE ALAGOAS', 'G16');

INSERT INTO GRUPOAFILIADA (ID, NOME, CODIGO) 
VALUES (HIBERNATE_SEQUENCE.nextVal,'REDE GLOBO', 'TVG');

INSERT INTO GRUPOAFILIADA (ID, NOME, CODIGO) 
VALUES (HIBERNATE_SEQUENCE.nextVal,'TV GRANDE RIO', 'G22');

INSERT INTO GRUPOAFILIADA (ID, NOME, CODIGO) 
VALUES (HIBERNATE_SEQUENCE.nextVal,'TV INTEGRAÇÃO', 'G19');

INSERT INTO GRUPOAFILIADA (ID, NOME, CODIGO) 
VALUES (HIBERNATE_SEQUENCE.nextVal,'REDE LIBERAL', 'G24');

INSERT INTO GRUPOAFILIADA (ID, NOME, CODIGO) 
VALUES (HIBERNATE_SEQUENCE.nextVal,'REDE MIRANTE', 'G25');

INSERT INTO GRUPOAFILIADA (ID, NOME, CODIGO) 
VALUES (HIBERNATE_SEQUENCE.nextVal,'TV BALSAS', 'G21');

INSERT INTO GRUPOAFILIADA (ID, NOME, CODIGO) 
VALUES (HIBERNATE_SEQUENCE.nextVal,'TV RIO SUL', 'G18');

INSERT INTO GRUPOAFILIADA (ID, NOME, CODIGO) 
VALUES (HIBERNATE_SEQUENCE.nextVal,'TV SERGIPE', 'G05');

INSERT INTO GRUPOAFILIADA (ID, NOME, CODIGO) 
VALUES (HIBERNATE_SEQUENCE.nextVal,'TV TAPAJÓS', 'G12');

INSERT INTO GRUPOAFILIADA (ID, NOME, CODIGO) 
VALUES (HIBERNATE_SEQUENCE.nextVal,'TV TEM', 'G07');

INSERT INTO GRUPOAFILIADA (ID, NOME, CODIGO) 
VALUES (HIBERNATE_SEQUENCE.nextVal,'TV TRIBUNA', 'G03');

INSERT INTO GRUPOAFILIADA (ID, NOME, CODIGO) 
VALUES (HIBERNATE_SEQUENCE.nextVal,'TV VERDES MARES', 'G20');

INSERT INTO GRUPOAFILIADA (ID, NOME, CODIGO) 
VALUES (HIBERNATE_SEQUENCE.nextVal,'REDE VANGUARDA', 'G04');

-- Insercao Afiliadas

INSERT INTO AFILIADA (ID, NOME, CODIGO, GRUPOAFILIADA_ID)  
SELECT HIBERNATE_SEQUENCE.nextVal,'EPTV CAMPINAS', 'CAM',G.ID FROM GRUPOAFILIADA G where CODIGO='G06';

INSERT INTO AFILIADA (ID, NOME, CODIGO, GRUPOAFILIADA_ID)  
SELECT HIBERNATE_SEQUENCE.nextVal,'EPTV CENTRAL', 'SCA',G.ID FROM GRUPOAFILIADA G where CODIGO='G06';

INSERT INTO AFILIADA (ID, NOME, CODIGO, GRUPOAFILIADA_ID)  
SELECT HIBERNATE_SEQUENCE.nextVal,'EPTV RIBEIRÃO', 'RIB',G.ID FROM GRUPOAFILIADA G where CODIGO='G06';

INSERT INTO AFILIADA (ID, NOME, CODIGO, GRUPOAFILIADA_ID)  
SELECT HIBERNATE_SEQUENCE.nextVal,'EPTV SUL DE MINAS', 'VAR',G.ID FROM GRUPOAFILIADA G where CODIGO='G06';

INSERT INTO AFILIADA (ID, NOME, CODIGO, GRUPOAFILIADA_ID)  
SELECT HIBERNATE_SEQUENCE.nextVal,'INTER TV ALTO LITORAL', 'CAB',G.ID FROM GRUPOAFILIADA G where CODIGO='G26';

INSERT INTO AFILIADA (ID, NOME, CODIGO, GRUPOAFILIADA_ID)  
SELECT HIBERNATE_SEQUENCE.nextVal,'INTER TV CABUGI', 'NAT',G.ID FROM GRUPOAFILIADA G where CODIGO='G26';

INSERT INTO AFILIADA (ID, NOME, CODIGO, GRUPOAFILIADA_ID)  
SELECT HIBERNATE_SEQUENCE.nextVal,'INTER TV COSTA BRANCA', 'NA2',G.ID FROM GRUPOAFILIADA G where CODIGO='G26';

INSERT INTO AFILIADA (ID, NOME, CODIGO, GRUPOAFILIADA_ID)  
SELECT HIBERNATE_SEQUENCE.nextVal,'INTER TV DOS VALES', 'FAB',G.ID FROM GRUPOAFILIADA G where CODIGO='G26';

INSERT INTO AFILIADA (ID, NOME, CODIGO, GRUPOAFILIADA_ID)  
SELECT HIBERNATE_SEQUENCE.nextVal,'INTER TV GRANDE MINAS', 'MTC',G.ID FROM GRUPOAFILIADA G where CODIGO='G26';

INSERT INTO AFILIADA (ID, NOME, CODIGO, GRUPOAFILIADA_ID)  
SELECT HIBERNATE_SEQUENCE.nextVal,'INTER TV PLANÍCIE', 'FLU',G.ID FROM GRUPOAFILIADA G where CODIGO='G26';

INSERT INTO AFILIADA (ID, NOME, CODIGO, GRUPOAFILIADA_ID)  
SELECT HIBERNATE_SEQUENCE.nextVal,'INTER TV SERRA MAR', 'FRI',G.ID FROM GRUPOAFILIADA G where CODIGO='G26';

INSERT INTO AFILIADA (ID, NOME, CODIGO, GRUPOAFILIADA_ID)  
SELECT HIBERNATE_SEQUENCE.nextVal,'RBS TV BAGÉ', 'BAG',G.ID FROM GRUPOAFILIADA G where CODIGO='G01';

INSERT INTO AFILIADA (ID, NOME, CODIGO, GRUPOAFILIADA_ID)  
SELECT HIBERNATE_SEQUENCE.nextVal,'RBS TV BLUMENAU', 'BLU',G.ID FROM GRUPOAFILIADA G where CODIGO='G01';

INSERT INTO AFILIADA (ID, NOME, CODIGO, GRUPOAFILIADA_ID)  
SELECT HIBERNATE_SEQUENCE.nextVal,'RBS TV CAXIAS DO SUL', 'CXS',G.ID FROM GRUPOAFILIADA G where CODIGO='G01';

INSERT INTO AFILIADA (ID, NOME, CODIGO, GRUPOAFILIADA_ID)  
SELECT HIBERNATE_SEQUENCE.nextVal,'RBS TV CENTRO-OESTE', 'JOA',G.ID FROM GRUPOAFILIADA G where CODIGO='G01';

INSERT INTO AFILIADA (ID, NOME, CODIGO, GRUPOAFILIADA_ID)  
SELECT HIBERNATE_SEQUENCE.nextVal,'RBS TV CHAPECÓ', 'CHA',G.ID FROM GRUPOAFILIADA G where CODIGO='G01';

INSERT INTO AFILIADA (ID, NOME, CODIGO, GRUPOAFILIADA_ID)  
SELECT HIBERNATE_SEQUENCE.nextVal,'RBS TV CRICIÚMA', 'CRI',G.ID FROM GRUPOAFILIADA G where CODIGO='G01';

INSERT INTO AFILIADA (ID, NOME, CODIGO, GRUPOAFILIADA_ID)  
SELECT HIBERNATE_SEQUENCE.nextVal,'RBS TV CRUZ ALTA', 'CAL',G.ID FROM GRUPOAFILIADA G where CODIGO='G01';

INSERT INTO AFILIADA (ID, NOME, CODIGO, GRUPOAFILIADA_ID)  
SELECT HIBERNATE_SEQUENCE.nextVal,'RBS TV ERECHIM', 'ERE',G.ID FROM GRUPOAFILIADA G where CODIGO='G01';

INSERT INTO AFILIADA (ID, NOME, CODIGO, GRUPOAFILIADA_ID)  
SELECT HIBERNATE_SEQUENCE.nextVal,'RBS TV FLORIANÓPOLIS', 'SC1',G.ID FROM GRUPOAFILIADA G where CODIGO='G01';

INSERT INTO AFILIADA (ID, NOME, CODIGO, GRUPOAFILIADA_ID)  
SELECT HIBERNATE_SEQUENCE.nextVal,'RBS TV JOINVILLE', 'JOI',G.ID FROM GRUPOAFILIADA G where CODIGO='G01';

INSERT INTO AFILIADA (ID, NOME, CODIGO, GRUPOAFILIADA_ID)  
SELECT HIBERNATE_SEQUENCE.nextVal,'RBS TV PASSO FUNDO', 'PFO',G.ID FROM GRUPOAFILIADA G where CODIGO='G01';

INSERT INTO AFILIADA (ID, NOME, CODIGO, GRUPOAFILIADA_ID)  
SELECT HIBERNATE_SEQUENCE.nextVal,'RBS TV PELOTAS', 'PEL',G.ID FROM GRUPOAFILIADA G where CODIGO='G01';

INSERT INTO AFILIADA (ID, NOME, CODIGO, GRUPOAFILIADA_ID)  
SELECT HIBERNATE_SEQUENCE.nextVal,'RBS TV PORTO ALEGRE', 'RS1',G.ID FROM GRUPOAFILIADA G where CODIGO='G01';

INSERT INTO AFILIADA (ID, NOME, CODIGO, GRUPOAFILIADA_ID)  
SELECT HIBERNATE_SEQUENCE.nextVal,'RBS TV RIO GRANDE', 'RGE',G.ID FROM GRUPOAFILIADA G where CODIGO='G01';

INSERT INTO AFILIADA (ID, NOME, CODIGO, GRUPOAFILIADA_ID)  
SELECT HIBERNATE_SEQUENCE.nextVal,'RBS TV SANTA CRUZ', 'STC',G.ID FROM GRUPOAFILIADA G where CODIGO='G01';

INSERT INTO AFILIADA (ID, NOME, CODIGO, GRUPOAFILIADA_ID)  
SELECT HIBERNATE_SEQUENCE.nextVal,'RBS TV SANTA MARIA', 'SMA',G.ID FROM GRUPOAFILIADA G where CODIGO='G01';

INSERT INTO AFILIADA (ID, NOME, CODIGO, GRUPOAFILIADA_ID)  
SELECT HIBERNATE_SEQUENCE.nextVal,'RBS TV SANTA ROSA', 'STR',G.ID FROM GRUPOAFILIADA G where CODIGO='G01';

INSERT INTO AFILIADA (ID, NOME, CODIGO, GRUPOAFILIADA_ID)  
SELECT HIBERNATE_SEQUENCE.nextVal,'RBS TV URUGUAIANA', 'URU',G.ID FROM GRUPOAFILIADA G where CODIGO='G01';

INSERT INTO AFILIADA (ID, NOME, CODIGO, GRUPOAFILIADA_ID)  
SELECT HIBERNATE_SEQUENCE.nextVal,'REDE AMAZÔNICA ARIQUEMES', 'ARI',G.ID FROM GRUPOAFILIADA G where CODIGO='G02';

INSERT INTO AFILIADA (ID, NOME, CODIGO, GRUPOAFILIADA_ID)  
SELECT HIBERNATE_SEQUENCE.nextVal,'REDE AMAZÔNICA BOA VISTA', 'ROR',G.ID FROM GRUPOAFILIADA G where CODIGO='G02';

INSERT INTO AFILIADA (ID, NOME, CODIGO, GRUPOAFILIADA_ID)  
SELECT HIBERNATE_SEQUENCE.nextVal,'REDE AMAZÔNICA CACOAL', 'COA',G.ID FROM GRUPOAFILIADA G where CODIGO='G02';

INSERT INTO AFILIADA (ID, NOME, CODIGO, GRUPOAFILIADA_ID)  
SELECT HIBERNATE_SEQUENCE.nextVal,'REDE AMAZÔNICA CRUZEIRO DO SUL', 'CZS',G.ID FROM GRUPOAFILIADA G where CODIGO='G02';

INSERT INTO AFILIADA (ID, NOME, CODIGO, GRUPOAFILIADA_ID)  
SELECT HIBERNATE_SEQUENCE.nextVal,'REDE AMAZÔNICA GUAJARÁ-MIRIM', 'GUA',G.ID FROM GRUPOAFILIADA G where CODIGO='G02';

INSERT INTO AFILIADA (ID, NOME, CODIGO, GRUPOAFILIADA_ID)  
SELECT HIBERNATE_SEQUENCE.nextVal,'REDE AMAZÔNICA ITACOATIARA', 'ITC',G.ID FROM GRUPOAFILIADA G where CODIGO='G02';

INSERT INTO AFILIADA (ID, NOME, CODIGO, GRUPOAFILIADA_ID)  
SELECT HIBERNATE_SEQUENCE.nextVal,'REDE AMAZÔNICA JI-PARANÁ', 'JIP',G.ID FROM GRUPOAFILIADA G where CODIGO='G02';

INSERT INTO AFILIADA (ID, NOME, CODIGO, GRUPOAFILIADA_ID)  
SELECT HIBERNATE_SEQUENCE.nextVal,'REDE AMAZÔNICA MACAPÁ', 'AMP',G.ID FROM GRUPOAFILIADA G where CODIGO='G02';

INSERT INTO AFILIADA (ID, NOME, CODIGO, GRUPOAFILIADA_ID)  
SELECT HIBERNATE_SEQUENCE.nextVal,'REDE AMAZÔNICA MANAUS', 'MAN',G.ID FROM GRUPOAFILIADA G where CODIGO='G02';

INSERT INTO AFILIADA (ID, NOME, CODIGO, GRUPOAFILIADA_ID)  
SELECT HIBERNATE_SEQUENCE.nextVal,'REDE AMAZÔNICA PARINTIS', 'PIN',G.ID FROM GRUPOAFILIADA G where CODIGO='G02';

INSERT INTO AFILIADA (ID, NOME, CODIGO, GRUPOAFILIADA_ID)  
SELECT HIBERNATE_SEQUENCE.nextVal,'REDE AMAZÔNICA PORTO VELHO', 'RON',G.ID FROM GRUPOAFILIADA G where CODIGO='G02';

INSERT INTO AFILIADA (ID, NOME, CODIGO, GRUPOAFILIADA_ID)  
SELECT HIBERNATE_SEQUENCE.nextVal,'REDE AMAZÔNICA RIO BRANCO', 'ACR',G.ID FROM GRUPOAFILIADA G where CODIGO='G02';

INSERT INTO AFILIADA (ID, NOME, CODIGO, GRUPOAFILIADA_ID)  
SELECT HIBERNATE_SEQUENCE.nextVal,'REDE AMAZÔNICA VILHENA', 'VLH',G.ID FROM GRUPOAFILIADA G where CODIGO='G02';

INSERT INTO AFILIADA (ID, NOME, CODIGO, GRUPOAFILIADA_ID)  
SELECT HIBERNATE_SEQUENCE.nextVal,'RPC CASCAVEL', 'CAV',G.ID FROM GRUPOAFILIADA G where CODIGO='G08';

INSERT INTO AFILIADA (ID, NOME, CODIGO, GRUPOAFILIADA_ID)  
SELECT HIBERNATE_SEQUENCE.nextVal,'RPC CURITIBA', 'CUR',G.ID FROM GRUPOAFILIADA G where CODIGO='G08';

INSERT INTO AFILIADA (ID, NOME, CODIGO, GRUPOAFILIADA_ID)  
SELECT HIBERNATE_SEQUENCE.nextVal,'RPC FOZ DO IGUAÇU', 'FOZ',G.ID FROM GRUPOAFILIADA G where CODIGO='G08';

INSERT INTO AFILIADA (ID, NOME, CODIGO, GRUPOAFILIADA_ID)  
SELECT HIBERNATE_SEQUENCE.nextVal,'RPC GUARAPUAVA', 'GAV',G.ID FROM GRUPOAFILIADA G where CODIGO='G08';

INSERT INTO AFILIADA (ID, NOME, CODIGO, GRUPOAFILIADA_ID)  
SELECT HIBERNATE_SEQUENCE.nextVal,'RPC LONDRINA', 'LON',G.ID FROM GRUPOAFILIADA G where CODIGO='G08';

INSERT INTO AFILIADA (ID, NOME, CODIGO, GRUPOAFILIADA_ID)  
SELECT HIBERNATE_SEQUENCE.nextVal,'RPC MARINGÁ', 'MAR',G.ID FROM GRUPOAFILIADA G where CODIGO='G08';

INSERT INTO AFILIADA (ID, NOME, CODIGO, GRUPOAFILIADA_ID)  
SELECT HIBERNATE_SEQUENCE.nextVal,'RPC PARANAVAÍ', 'PR3',G.ID FROM GRUPOAFILIADA G where CODIGO='G08';

INSERT INTO AFILIADA (ID, NOME, CODIGO, GRUPOAFILIADA_ID)  
SELECT HIBERNATE_SEQUENCE.nextVal,'RPC PONTA GROSSA', 'PGR',G.ID FROM GRUPOAFILIADA G where CODIGO='G08';

INSERT INTO AFILIADA (ID, NOME, CODIGO, GRUPOAFILIADA_ID)  
SELECT HIBERNATE_SEQUENCE.nextVal,'TV ALVORADA DO SUL', 'FNO',G.ID FROM GRUPOAFILIADA G where CODIGO='G23';

INSERT INTO AFILIADA (ID, NOME, CODIGO, GRUPOAFILIADA_ID)  
SELECT HIBERNATE_SEQUENCE.nextVal,'TV ANHANGUERA ANAPOLIS', 'GO2',G.ID FROM GRUPOAFILIADA G where CODIGO='G09';

INSERT INTO AFILIADA (ID, NOME, CODIGO, GRUPOAFILIADA_ID)  
SELECT HIBERNATE_SEQUENCE.nextVal,'TV ANHANGUERA CATALÃO', 'CAT',G.ID FROM GRUPOAFILIADA G where CODIGO='G09';

INSERT INTO AFILIADA (ID, NOME, CODIGO, GRUPOAFILIADA_ID)  
SELECT HIBERNATE_SEQUENCE.nextVal,'TV ANHANGUERA DE ARAGUAÍNA', 'INA',G.ID FROM GRUPOAFILIADA G where CODIGO='G09';

INSERT INTO AFILIADA (ID, NOME, CODIGO, GRUPOAFILIADA_ID)  
SELECT HIBERNATE_SEQUENCE.nextVal,'TV ANHANGUERA GOIÂNIA', 'GO1',G.ID FROM GRUPOAFILIADA G where CODIGO='G09';

INSERT INTO AFILIADA (ID, NOME, CODIGO, GRUPOAFILIADA_ID)  
SELECT HIBERNATE_SEQUENCE.nextVal,'TV ANHANGUERA GURUPI', 'GUR',G.ID FROM GRUPOAFILIADA G where CODIGO='G09';

INSERT INTO AFILIADA (ID, NOME, CODIGO, GRUPOAFILIADA_ID)  
SELECT HIBERNATE_SEQUENCE.nextVal,'TV ANHANGUERA ITUMBIARA', 'IBI',G.ID FROM GRUPOAFILIADA G where CODIGO='G09';

INSERT INTO AFILIADA (ID, NOME, CODIGO, GRUPOAFILIADA_ID)  
SELECT HIBERNATE_SEQUENCE.nextVal,'TV ANHANGUERA JATAÍ', 'JAT',G.ID FROM GRUPOAFILIADA G where CODIGO='G09';

INSERT INTO AFILIADA (ID, NOME, CODIGO, GRUPOAFILIADA_ID)  
SELECT HIBERNATE_SEQUENCE.nextVal,'TV ANHANGUERA LUZIANIA', 'LZA',G.ID FROM GRUPOAFILIADA G where CODIGO='G09';

INSERT INTO AFILIADA (ID, NOME, CODIGO, GRUPOAFILIADA_ID)  
SELECT HIBERNATE_SEQUENCE.nextVal,'TV ANHANGUERA PALMAS', 'PAL',G.ID FROM GRUPOAFILIADA G where CODIGO='G09';

INSERT INTO AFILIADA (ID, NOME, CODIGO, GRUPOAFILIADA_ID)  
SELECT HIBERNATE_SEQUENCE.nextVal,'TV ANHANGUERA PORANGATU', 'PRT',G.ID FROM GRUPOAFILIADA G where CODIGO='G09';

INSERT INTO AFILIADA (ID, NOME, CODIGO, GRUPOAFILIADA_ID)  
SELECT HIBERNATE_SEQUENCE.nextVal,'TV ANHANGUERA RIO VERDE', 'RVD',G.ID FROM GRUPOAFILIADA G where CODIGO='G09';

INSERT INTO AFILIADA (ID, NOME, CODIGO, GRUPOAFILIADA_ID)  
SELECT HIBERNATE_SEQUENCE.nextVal,'TV ASA BRANCA', 'CRR',G.ID FROM GRUPOAFILIADA G where CODIGO='G27';

INSERT INTO AFILIADA (ID, NOME, CODIGO, GRUPOAFILIADA_ID)  
SELECT HIBERNATE_SEQUENCE.nextVal,'TV BAHIA', 'SAL',G.ID FROM GRUPOAFILIADA G where CODIGO='G00';

INSERT INTO AFILIADA (ID, NOME, CODIGO, GRUPOAFILIADA_ID)  
SELECT HIBERNATE_SEQUENCE.nextVal,'TV CABO BRANCO', 'JP',G.ID FROM GRUPOAFILIADA G where CODIGO='G17';

INSERT INTO AFILIADA (ID, NOME, CODIGO, GRUPOAFILIADA_ID)  
SELECT HIBERNATE_SEQUENCE.nextVal,'TV CENTRO AMÉRICA -  TANGARÁ DA SERRA', 'TGS',G.ID FROM GRUPOAFILIADA G where CODIGO='G13';

INSERT INTO AFILIADA (ID, NOME, CODIGO, GRUPOAFILIADA_ID)  
SELECT HIBERNATE_SEQUENCE.nextVal,'TV CENTRO AMÉRICA - SINOP', 'SNO',G.ID FROM GRUPOAFILIADA G where CODIGO='G13';

INSERT INTO AFILIADA (ID, NOME, CODIGO, GRUPOAFILIADA_ID)  
SELECT HIBERNATE_SEQUENCE.nextVal,'TV CENTRO AMÉRICA RONDONÓPOLIS', 'ROD',G.ID FROM GRUPOAFILIADA G where CODIGO='G13';

INSERT INTO AFILIADA (ID, NOME, CODIGO, GRUPOAFILIADA_ID)  
SELECT HIBERNATE_SEQUENCE.nextVal,'TV CENTRO-AMÉRICA CUIABÁ', 'MT',G.ID FROM GRUPOAFILIADA G where CODIGO='G13';

INSERT INTO AFILIADA (ID, NOME, CODIGO, GRUPOAFILIADA_ID)  
SELECT HIBERNATE_SEQUENCE.nextVal,'TV CLUBE', 'TER',G.ID FROM GRUPOAFILIADA G where CODIGO='G23';

INSERT INTO AFILIADA (ID, NOME, CODIGO, GRUPOAFILIADA_ID)  
SELECT HIBERNATE_SEQUENCE.nextVal,'TV DIÁRIO', 'MOC',G.ID FROM GRUPOAFILIADA G where CODIGO='G11';

INSERT INTO AFILIADA (ID, NOME, CODIGO, GRUPOAFILIADA_ID)  
SELECT HIBERNATE_SEQUENCE.nextVal,'TV FRONTEIRA', 'PRP',G.ID FROM GRUPOAFILIADA G where CODIGO='G15';

INSERT INTO AFILIADA (ID, NOME, CODIGO, GRUPOAFILIADA_ID)  
SELECT HIBERNATE_SEQUENCE.nextVal,'TV GAZETA', 'VIT',G.ID FROM GRUPOAFILIADA G where CODIGO='G10';

INSERT INTO AFILIADA (ID, NOME, CODIGO, GRUPOAFILIADA_ID)  
SELECT HIBERNATE_SEQUENCE.nextVal,'TV GAZETA DE ALAGOAS', 'MAC',G.ID FROM GRUPOAFILIADA G where CODIGO='G16';

INSERT INTO AFILIADA (ID, NOME, CODIGO, GRUPOAFILIADA_ID)  
SELECT HIBERNATE_SEQUENCE.nextVal,'TV GAZETA NOROESTE', 'COL',G.ID FROM GRUPOAFILIADA G where CODIGO='G10';

INSERT INTO AFILIADA (ID, NOME, CODIGO, GRUPOAFILIADA_ID)  
SELECT HIBERNATE_SEQUENCE.nextVal,'TV GAZETA NORTE', 'ES2',G.ID FROM GRUPOAFILIADA G where CODIGO='G10';

INSERT INTO AFILIADA (ID, NOME, CODIGO, GRUPOAFILIADA_ID)  
SELECT HIBERNATE_SEQUENCE.nextVal,'TV GAZETA SUL', 'CAC',G.ID FROM GRUPOAFILIADA G where CODIGO='G10';

INSERT INTO AFILIADA (ID, NOME, CODIGO, GRUPOAFILIADA_ID)  
SELECT HIBERNATE_SEQUENCE.nextVal,'TV GLOBO BRASÍLIA', 'DF',G.ID FROM GRUPOAFILIADA G where CODIGO='TVG';

INSERT INTO AFILIADA (ID, NOME, CODIGO, GRUPOAFILIADA_ID)  
SELECT HIBERNATE_SEQUENCE.nextVal,'TV GLOBO MINAS', 'BH',G.ID FROM GRUPOAFILIADA G where CODIGO='TVG';

INSERT INTO AFILIADA (ID, NOME, CODIGO, GRUPOAFILIADA_ID)  
SELECT HIBERNATE_SEQUENCE.nextVal,'TV GLOBO NORDESTE', 'PE1',G.ID FROM GRUPOAFILIADA G where CODIGO='TVG';

INSERT INTO AFILIADA (ID, NOME, CODIGO, GRUPOAFILIADA_ID)  
SELECT HIBERNATE_SEQUENCE.nextVal,'TV GLOBO RIO', 'RJ',G.ID FROM GRUPOAFILIADA G where CODIGO='TVG';

INSERT INTO AFILIADA (ID, NOME, CODIGO, GRUPOAFILIADA_ID)  
SELECT HIBERNATE_SEQUENCE.nextVal,'TV GLOBO SÃO PAULO', 'SP1',G.ID FROM GRUPOAFILIADA G where CODIGO='TVG';

INSERT INTO AFILIADA (ID, NOME, CODIGO, GRUPOAFILIADA_ID)  
SELECT HIBERNATE_SEQUENCE.nextVal,'TV GRANDE RIO', 'PET',G.ID FROM GRUPOAFILIADA G where CODIGO='G22';

INSERT INTO AFILIADA (ID, NOME, CODIGO, GRUPOAFILIADA_ID)  
SELECT HIBERNATE_SEQUENCE.nextVal,'TV INTEGRAÇÃO ARAXÁ', 'AXA',G.ID FROM GRUPOAFILIADA G where CODIGO='G19';

INSERT INTO AFILIADA (ID, NOME, CODIGO, GRUPOAFILIADA_ID)  
SELECT HIBERNATE_SEQUENCE.nextVal,'TV INTEGRAÇÃO ITUIUTABA', 'ITU',G.ID FROM GRUPOAFILIADA G where CODIGO='G19';

INSERT INTO AFILIADA (ID, NOME, CODIGO, GRUPOAFILIADA_ID)  
SELECT HIBERNATE_SEQUENCE.nextVal,'TV INTEGRAÇÃO JUIZ DE FORA', 'JF',G.ID FROM GRUPOAFILIADA G where CODIGO='G19';

INSERT INTO AFILIADA (ID, NOME, CODIGO, GRUPOAFILIADA_ID)  
SELECT HIBERNATE_SEQUENCE.nextVal,'TV INTEGRAÇÃO UBERLÂNDIA', 'UBE',G.ID FROM GRUPOAFILIADA G where CODIGO='G19';

INSERT INTO AFILIADA (ID, NOME, CODIGO, GRUPOAFILIADA_ID)  
SELECT HIBERNATE_SEQUENCE.nextVal,'TV LIBERAL ALTAMIRA', 'ALT',G.ID FROM GRUPOAFILIADA G where CODIGO='G24';

INSERT INTO AFILIADA (ID, NOME, CODIGO, GRUPOAFILIADA_ID) 
SELECT HIBERNATE_SEQUENCE.nextVal,'TV LIBERAL BELÉM', 'BEL',G.ID FROM GRUPOAFILIADA G where CODIGO='G24';

INSERT INTO AFILIADA (ID, NOME, CODIGO, GRUPOAFILIADA_ID) 
SELECT HIBERNATE_SEQUENCE.nextVal,'TV LIBERAL CASTANHAL', 'CAS',G.ID FROM GRUPOAFILIADA G where CODIGO='G24';

INSERT INTO AFILIADA (ID, NOME, CODIGO, GRUPOAFILIADA_ID) 
SELECT HIBERNATE_SEQUENCE.nextVal,'TV LIBERAL ITAITUBA', 'ITT',G.ID FROM GRUPOAFILIADA G where CODIGO='G24';

INSERT INTO AFILIADA (ID, NOME, CODIGO, GRUPOAFILIADA_ID) 
SELECT HIBERNATE_SEQUENCE.nextVal,'TV LIBERAL MARABÁ', 'MAB',G.ID FROM GRUPOAFILIADA G where CODIGO='G24';

INSERT INTO AFILIADA (ID, NOME, CODIGO, GRUPOAFILIADA_ID) 
SELECT HIBERNATE_SEQUENCE.nextVal,'TV LIBERAL PARAGOMINAS', 'PAM',G.ID FROM GRUPOAFILIADA G where CODIGO='G24';

INSERT INTO AFILIADA (ID, NOME, CODIGO, GRUPOAFILIADA_ID) 
SELECT HIBERNATE_SEQUENCE.nextVal,'TV LIBERAL PARAUAPEBAS', 'PUP',G.ID FROM GRUPOAFILIADA G where CODIGO='G24';

INSERT INTO AFILIADA (ID, NOME, CODIGO, GRUPOAFILIADA_ID)  
SELECT HIBERNATE_SEQUENCE.nextVal,'TV LIBERAL REDENÇÃO', 'RDC',G.ID FROM GRUPOAFILIADA G where CODIGO='G24';

INSERT INTO AFILIADA (ID, NOME, CODIGO, GRUPOAFILIADA_ID)  
SELECT HIBERNATE_SEQUENCE.nextVal,'TV LIBERAL TUCURUÍ', 'TUC',G.ID FROM GRUPOAFILIADA G where CODIGO='G24';

INSERT INTO AFILIADA (ID, NOME, CODIGO, GRUPOAFILIADA_ID) 
SELECT HIBERNATE_SEQUENCE.nextVal,'TV MIRANTE AÇAILÂNDIA', 'ACA',G.ID FROM GRUPOAFILIADA G where CODIGO='G25';

INSERT INTO AFILIADA (ID, NOME, CODIGO, GRUPOAFILIADA_ID) 
SELECT HIBERNATE_SEQUENCE.nextVal,'TV MIRANTE BALSAS', 'BAS',G.ID FROM GRUPOAFILIADA G where CODIGO='G21';

INSERT INTO AFILIADA (ID, NOME, CODIGO, GRUPOAFILIADA_ID) 
SELECT HIBERNATE_SEQUENCE.nextVal,'TV MIRANTE COCAIS', 'CDO',G.ID FROM GRUPOAFILIADA G where CODIGO='G25';

INSERT INTO AFILIADA (ID, NOME, CODIGO, GRUPOAFILIADA_ID) 
SELECT HIBERNATE_SEQUENCE.nextVal,'TV MIRANTE IMPERATRIZ', 'IMP',G.ID FROM GRUPOAFILIADA G where CODIGO='G25';

INSERT INTO AFILIADA (ID, NOME, CODIGO, GRUPOAFILIADA_ID) 
SELECT HIBERNATE_SEQUENCE.nextVal,'TV MIRANTE SANTA INÊS', 'STI',G.ID FROM GRUPOAFILIADA G where CODIGO='G25';

INSERT INTO AFILIADA (ID, NOME, CODIGO, GRUPOAFILIADA_ID) 
SELECT HIBERNATE_SEQUENCE.nextVal,'TV MIRANTE SÃO LUIZ', 'MA1',G.ID FROM GRUPOAFILIADA G where CODIGO='G25';

INSERT INTO AFILIADA (ID, NOME, CODIGO, GRUPOAFILIADA_ID) 
SELECT HIBERNATE_SEQUENCE.nextVal,'TV MORENA CAMPO GRANDE', 'MS1',G.ID FROM GRUPOAFILIADA G where CODIGO='G13';

INSERT INTO AFILIADA (ID, NOME, CODIGO, GRUPOAFILIADA_ID) 
SELECT HIBERNATE_SEQUENCE.nextVal,'TV MORENA CORUMBÁ', 'MS2',G.ID FROM GRUPOAFILIADA G where CODIGO='G13';

INSERT INTO AFILIADA (ID, NOME, CODIGO, GRUPOAFILIADA_ID) 
SELECT HIBERNATE_SEQUENCE.nextVal,'TV MORENA PONTA PORÃ', 'POR',G.ID FROM GRUPOAFILIADA G where CODIGO='G13';

INSERT INTO AFILIADA (ID, NOME, CODIGO, GRUPOAFILIADA_ID) 
SELECT HIBERNATE_SEQUENCE.nextVal,'TV OESTE', 'BAR',G.ID FROM GRUPOAFILIADA G where CODIGO='G00';

INSERT INTO AFILIADA (ID, NOME, CODIGO, GRUPOAFILIADA_ID) 
SELECT HIBERNATE_SEQUENCE.nextVal,'TV PARAÍBA', 'CPG',G.ID FROM GRUPOAFILIADA G where CODIGO='G17';

INSERT INTO AFILIADA (ID, NOME, CODIGO, GRUPOAFILIADA_ID) 
SELECT HIBERNATE_SEQUENCE.nextVal,'TV RIO SUL', 'RES',G.ID FROM GRUPOAFILIADA G where CODIGO='G18';

INSERT INTO AFILIADA (ID, NOME, CODIGO, GRUPOAFILIADA_ID) 
SELECT HIBERNATE_SEQUENCE.nextVal,'TV SANTA CRUZ', 'ITA',G.ID FROM GRUPOAFILIADA G where CODIGO='G00';

INSERT INTO AFILIADA (ID, NOME, CODIGO, GRUPOAFILIADA_ID) 
SELECT HIBERNATE_SEQUENCE.nextVal,'TV SÃO FRANCISCO', 'JUA',G.ID FROM GRUPOAFILIADA G where CODIGO='G00';

INSERT INTO AFILIADA (ID, NOME, CODIGO, GRUPOAFILIADA_ID) 
SELECT HIBERNATE_SEQUENCE.nextVal,'TV SERGIPE', 'SER',G.ID FROM GRUPOAFILIADA G where CODIGO='G05';

INSERT INTO AFILIADA (ID, NOME, CODIGO, GRUPOAFILIADA_ID) 
SELECT HIBERNATE_SEQUENCE.nextVal,'TV SUBAÉ', 'FEI',G.ID FROM GRUPOAFILIADA G where CODIGO='G00';

INSERT INTO AFILIADA (ID, NOME, CODIGO, GRUPOAFILIADA_ID) 
SELECT HIBERNATE_SEQUENCE.nextVal,'TV SUDOESTE', 'VDC',G.ID FROM GRUPOAFILIADA G where CODIGO='G00';

INSERT INTO AFILIADA (ID, NOME, CODIGO, GRUPOAFILIADA_ID) 
SELECT HIBERNATE_SEQUENCE.nextVal,'TV TAPAJÓS', 'TAP',G.ID FROM GRUPOAFILIADA G where CODIGO='G12';

INSERT INTO AFILIADA (ID, NOME, CODIGO, GRUPOAFILIADA_ID) 
SELECT HIBERNATE_SEQUENCE.nextVal,'TV TEM BAURU', 'BAU',G.ID FROM GRUPOAFILIADA G where CODIGO='G07';

INSERT INTO AFILIADA (ID, NOME, CODIGO, GRUPOAFILIADA_ID) 
SELECT HIBERNATE_SEQUENCE.nextVal,'TV TEM ITAPETININGA', 'ITP',G.ID FROM GRUPOAFILIADA G where CODIGO='G07';

INSERT INTO AFILIADA (ID, NOME, CODIGO, GRUPOAFILIADA_ID) 
SELECT HIBERNATE_SEQUENCE.nextVal,'TV TEM SÃO JOSÉ DO RIO PRETO', 'SJR',G.ID FROM GRUPOAFILIADA G where CODIGO='G07';

INSERT INTO AFILIADA (ID, NOME, CODIGO, GRUPOAFILIADA_ID) 
SELECT HIBERNATE_SEQUENCE.nextVal,'TV TEM SOROCABA', 'SOR',G.ID FROM GRUPOAFILIADA G where CODIGO='G07';

INSERT INTO AFILIADA (ID, NOME, CODIGO, GRUPOAFILIADA_ID) 
SELECT HIBERNATE_SEQUENCE.nextVal,'TV TRIBUNA', 'SAN',G.ID FROM GRUPOAFILIADA G where CODIGO='G03';

INSERT INTO AFILIADA (ID, NOME, CODIGO, GRUPOAFILIADA_ID) 
SELECT HIBERNATE_SEQUENCE.nextVal,'TV VERDES MARES CARIRI', 'CE2',G.ID FROM GRUPOAFILIADA G where CODIGO='G20';

INSERT INTO AFILIADA (ID, NOME, CODIGO, GRUPOAFILIADA_ID) 
SELECT HIBERNATE_SEQUENCE.nextVal,'TV VERDES MARES FORTALEZA', 'CE1',G.ID FROM GRUPOAFILIADA G where CODIGO='G20';

INSERT INTO AFILIADA (ID, NOME, CODIGO, GRUPOAFILIADA_ID) 
SELECT HIBERNATE_SEQUENCE.nextVal,'VANGUARDA SÃO JOSÉ DOS CAMPOS', 'SJC',G.ID FROM GRUPOAFILIADA G where CODIGO='G04';

INSERT INTO AFILIADA (ID, NOME, CODIGO, GRUPOAFILIADA_ID) 
SELECT HIBERNATE_SEQUENCE.nextVal,'VANGUARDA TAUBATÉ', 'TAU',G.ID FROM GRUPOAFILIADA G where CODIGO='G04';

Commit;
