ALTER TABLE USUARIO ADD TELEFONE VARCHAR2(50);

DROP TABLE CONFIGURACAOSMS;
CREATE TABLE CONFIGURACAOSMS (
	ID decimal(19,0) PRIMARY KEY NOT NULL,	
	ACCESSKEYID VARCHAR2(180),	
	SECRETACCESSKEY VARCHAR2(180)
);

INSERT INTO CONFIGURACAOSMS (ID, ACCESSKEYID, SECRETACCESSKEY) VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'AKIAJYDSDZW7EUWKF2YA', '9OwpjsxVz6gOIg0sxkdMxxCJcYspjoIQnkDIA+nb');