ALTER TABLE SIDI.CANAL ADD RELACIONADO_ID DECIMAL(19,0) NULL

ALTER TABLE "SIDI"."CANAL"
ADD CONSTRAINT FK_CANAL_RELACIONADO
FOREIGN KEY (RELACIONADO_ID)
REFERENCES "SIDI"."CANAL"(ID)

DELETE SIDI.DISTRIBUICAOOPERADORA
WHERE DISTRIBUICAOPRINCIPAL_ID IN (SELECT MAX(ID) AS QTD FROM SIDI.DISTRIBUICAOPRINCIPAL
GROUP BY CANAL_ID, EVENTO_ID
HAVING COUNT(*) > 1);

DELETE SIDI.DISTRIBUICAOESTADO
WHERE DISTRIBPRINCIPALID IN (SELECT MAX(ID) AS QTD FROM SIDI.DISTRIBUICAOPRINCIPAL
GROUP BY CANAL_ID, EVENTO_ID
HAVING COUNT(*) > 1);

DELETE SIDI.DISTRIBUICAOPRINCIPAL
WHERE ID IN (SELECT MAX(ID) AS QTD FROM SIDI.DISTRIBUICAOPRINCIPAL
GROUP BY CANAL_ID, EVENTO_ID
HAVING COUNT(*) > 1);

ALTER TABLE SIDI.DISTRIBUICAOPRINCIPAL ADD CONSTRAINT DISTPRINC_CANAL_EVENTO UNIQUE (CANAL_ID, EVENTO_ID);