ALTER TABLE "SIDI"."DISTRIBUICAOOPERADORA"
add DISTRIBUICAOPRINCIPAL_ID decimal(19,0);

ALTER TABLE "SIDI"."DISTRIBUICAOPRINCIPAL"
add ALTERADOOPERADORA decimal(10,0) DEFAULT 1;

UPDATE "SIDI"."CANAL"
SET COR = '#696960'
WHERE NOME = 'PREMIERE CLUBES';