CREATE TABLE SIDI.LOG 
(
  ID NUMBER(19,0) NOT NULL,
  CLASSE VARCHAR(255) NOT NULL,
  METODO VARCHAR(255) NOT NULL,
  USUARIO VARCHAR(255) NOT NULL,
  DATA DATE NOT NULL, 
  
  CONSTRAINT LOGpk PRIMARY KEY (ID)
);