ALTER TABLE SIDI.OPERADORA
ADD MATRIZ VARCHAR2(20) NULL;

CREATE TABLE OPERADORACANALLINEUP
(
   OPERADORA_ID decimal(19,0) NOT NULL,
   CANAIS_ID decimal(19,0) NOT NULL,
   ID decimal(19,0) PRIMARY KEY NOT NULL,
   LINEUP decimal(19,0),
   MATRIZ varchar2(20)
);

CREATE UNIQUE INDEX UNIQUE_OPER_CANAL_LINEUP ON OPERADORACANALLINEUP
(
  OPERADORA_ID,
  CANAIS_ID
);

INSERT INTO OPERADORACANALLINEUP (OPERADORA_ID, CANAIS_ID, ID) 
(SELECT OPERADORA_ID, CANAIS_ID, HIBERNATE_SEQUENCE.NEXTVAL FROM OPERADORA_CANAL);

UPDATE (SELECT OPERADORACANALLINEUP.MATRIZ AS A, OPERADORA.MATRIZ AS B FROM OPERADORACANALLINEUP  
INNER JOIN OPERADORA ON OPERADORACANALLINEUP.OPERADORA_ID = OPERADORA.ID)
SET A = B;

ALTER TABLE CAMPEONATO ADD PESO NUMBER(19,2);
ALTER TABLE FASE ADD PESO NUMBER(19,2);

ALTER TABLE PESOCLUBEESTADO RENAME COLUMN PESO to BKP_PESO;
ALTER TABLE PESOCLUBEESTADO ADD PESO NUMBER(10, 2);

CREATE TABLE pesosistema (
  ID decimal(19,0) PRIMARY KEY NOT NULL,
  pesoCampeonato NUMBER(10, 2),
  pesoTorcida NUMBER(10, 2)
)