--DROP TABLE "SIDI"."DIST_PRINC_AFILIADA";
CREATE TABLE "SIDI"."DIST_PRINC_AFILIADA"
(
   DIST_PRINC_ID decimal(19,0) NOT NULL,
   AFILIADA_ID decimal(19,0) NOT NULL
);

ALTER TABLE "SIDI"."DIST_PRINC_AFILIADA"
ADD CONSTRAINT DIST_PRINC_AFILIADA_COMFK
FOREIGN KEY (DIST_PRINC_ID)
REFERENCES "SIDI"."DISTRIBUICAOPRINCIPAL"(ID);

ALTER TABLE "SIDI"."DIST_PRINC_AFILIADA"
ADD CONSTRAINT DIST_PRINC_AFILIADA_AFIFK
FOREIGN KEY (AFILIADA_ID)
REFERENCES "SIDI"."AFILIADA"(ID);
