ALTER TABLE SIDI.OPERADORA_CANAL ADD  IDENTIFICADOR DECIMAL(19,0);


UPDATE SIDI.OPERADORA_CANAL SET IDENTIFICADOR = HIBERNATE_SEQUENCE.NEXTVAL;


DELETE FROM  SIDI.OPERADORA_CANAL WHERE IDENTIFICADOR NOT IN (
	SELECT MIN(IDENTIFICADOR) AS IDENT FROM SIDI.OPERADORA_CANAL OPCN JOIN SIDI.CANAL CN ON (OPCN.CANAIS_ID = CN.ID)
	GROUP BY OPERADORA_ID, CANAIS_ID
);


ALTER TABLE OPERADORA_CANAL ADD CONSTRAINT UNIQUE_OPER_CANAL UNIQUE (OPERADORA_ID, CANAIS_ID);


ALTER TABLE SIDI.OPERADORA_CANAL DROP COLUMN IDENTIFICADOR;


DELETE FROM SIDI.DISTRIBUICAOOPERADORA WHERE DISTRIBUICAOPRINCIPAL_ID NOT IN (SELECT ID FROM SIDI.DISTRIBUICAOPRINCIPAL);


ALTER TABLE SIDI.DISTRIBUICAOOPERADORA
ADD CONSTRAINT DISTRIOPER_DISTPRINCIPAL FOREIGN KEY (DISTRIBUICAOPRINCIPAL_ID) REFERENCES SIDI.DISTRIBUICAOPRINCIPAL (ID);

